services:
  cargo-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:mysecretpassword@db:3306/cargo
      - CRYPTO_KEY=980e0e27cc9525cc3fbf9c0c21883fe0de5edfeee958398ca56b6c54b5cd5e5b

  db:
    image: mariadb:10.11
    container_name: cargo-server-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: cargo
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
